version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://database:27017/mydb
  database:
    build:
      context: ./database
    ports:
      - '27017:27017'